### ISSUE TITLE
Set option PDO::ATTR_TIMEOUT

### ISSUE THREAD

**Issue by vsoaresz** [harrygulliford/laravel-firebird#10]
How i set option PDO::ATTR_TIMEOUT to connection?

**Comment by mariuz** [comment]
It's not implemented yet 

https://stackoverflow.com/questions/7453527/php-pdo-set-firebird-connection-timeout/7453917#7453917

**Comment by vsoaresz** [comment]
thank you!

**Comment by harrygulliford** [comment]
Thanks @mariuz for helping out!
