### ISSUE TITLE
Lastinsertid support?

### ISSUE THREAD

**Issue by luni23** [harrygulliford/laravel-firebird#11]
I have a project with the original version of this driver by jacquestvanzuydam and it didn't support lastinsertid firebird function. I don't want to make changes just to try if this fork works with that. ¿Anyone knows if lastinsertid is working on this fork? 
Reference: https://github.com/jacquestvanzuydam/laravel-firebird/issues/25#issuecomment-216392037

Thanks!

**Comment by harrygulliford** [comment]
It appears that the Firebird/Interbase PHP PDO driver does not support the `lastInsertId()` method as shown here: https://github.com/jacquestvanzuydam/laravel-firebird/issues/25#issuecomment-216444137

I'd be open to accepting a PR to add this functionality to the package. Here is how Laravel implements it for SQL Server: https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Query/Processors/SqlServerProcessor.php
