### ISSUE TITLE
laravel-firebird dialect 1

### ISSUE THREAD

**Issue by wik1** [harrygulliford/laravel-firebird#12]
Hi,
Is annybody know is the harrygulliford driver working with firebird dialect 1. 
This is differens, how sql interpreting query e.g. 
SELECT * FROM "migration" 
is ok in dialect 3 but in dialect 1 shoud be 
SELECT * from migration.
If we execute SELECT * FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = ?
parameter "?" shoud be uppercased

Best Regards
Wiesiek

**Comment by harrygulliford** [comment]
@wik1 Dialect 1 isn't supported, as it was only originally intended for legacy applications to migrate from InterBase 5 to Firebird 1.
