### ISSUE TITLE
Failed migrations on Laravel 6.x

### ISSUE THREAD

**Issue by qlixes** [harrygulliford/laravel-firebird#13]
first, I'm using **Laravel 6.0**, then tried to install [laravel-firebird](harrygulliford/laravel-firebird). 
I've found some error :
1. failed to migrations
```
        Schema::create('roles', function (Blueprint $table) {
            $table->useIdentity();
            $table->bigIncrements('id');
            $table->string('role_name')->unique();
            $table->boolean('all_branch')->default(false)->comment('access all branch');
            $table->boolean('is_active')->default(true);
            $table->timestamps();
        });
```
because on Firebird Grammer, while had default value, it's doesn't need NOT NULL again.

Thank you a lot.

**Comment by harrygulliford** [comment]
@qlixes Migrations aren't something that has been properly tested and I should probably add a warning in the readme. If you do require it, I'm open to PRs.
