### ISSUE TITLE
Illuminate\Database\QueryException could not find driver

### ISSUE THREAD

**Issue by rlucasfm** [harrygulliford/laravel-firebird#18]
Trying to do a simple query, just to test if the connection with Firebird database works, and got the following error.
"Illuminate\Database\QueryException could not find driver". Already have the firebird extension enabled on PHP and fbclient.dll on the PHP folder, what could it be?

**Comment by rlucasfm** [comment]
Problem with the pdo_firebird being not loaded by PHP. Sadly had to downgrade from PHP 8 to 7.3, and yet some issues to make the extension to work, but it does

**Comment by harrygulliford** [comment]
The Firebird PHP extension was updated to support PHP 8 as of v1.1.0 https://github.com/FirebirdSQL/php-firebird/releases
