### ISSUE TITLE
Queues with Firebird

### ISSUE THREAD

**Issue by bru95** [harrygulliford/laravel-firebird#19]
Hi,

I need use Laravel Queues, and the driver 'database' is the best option to me, but this package not work with migrations. So the commands:
php artisan queue:table
php artisan migrate
are not working.

Has anyone faced this or can help me?

Thanks.

**Comment by bru95** [comment]
I created the table manually, but as the columns are capitalized, it didn't work either.

**Comment by harrygulliford** [comment]
This package doesn't support database migrations. Please see the [limitations section in the readme](https://github.com/harrygulliford/laravel-firebird#limitations).
