### ISSUE TITLE
Using Firebird for jobs - driver doesn't support lastInsertId()

### ISSUE THREAD

**Issue by qwasyx0** [harrygulliford/laravel-firebird#27]
Hello I would like to use a firebird database for queued jobs, migration was successful, but when inserting to the table, I get error:

```
SQLSTATE[IM001]: Driver does not support this function: driver does not support lastInsertId()
```

With models, I was able to call the database sequence generator, but this is code of laravel that I know I should never alter. Is it possible to have jobs in firebird?

**Comment by vkrapotkin** [comment]
Yes. I faced this too but right on the start. 
I've started a new project on already existing database with a TALL stack. 
So I cannot even register new user.

**Comment by harrygulliford** [comment]
It isn't a limitation of this package, but rather the Firebird PDO driver itself doesn't have support the `lastInsertId()` function.

One option is setting `public $incrementing = false;` on the model and setting the value of the id explicitly (to the value returned from calling the sequence generator) when creating a new record.

If you have any code examples regarding how we can support auto-incrementing primary keys in this package, I'd be happy to try and implement it.

**Comment by last1971** [comment]
trait InsertTrait
{
    protected function insertAndSetId(Builder $query, $attributes)
    {
        $nextSequenceId = $this->nextSequenceId();
        $query->insert(array_merge($attributes, [$this->getKeyName() => $nextSequenceId]));
        $this->setAttribute($this->getKeyName(), $nextSequenceId);
    }

    protected function nextSequenceId()
    {
        $result = $this->getConnection()
            ->table('RDB$DATABASE')
            ->select($this->getConnection()->raw("COALESCE( GEN_ID( $this->sequenceName, 1 ), 1 ) AS ID"))
            ->get();
        return $result[0]->ID;
    }
}
