### ISSUE TITLE
Querys with exists and union all don't work

### ISSUE THREAD

**Issue by rafaels86** [harrygulliford/laravel-firebird#28]
There is an error in sqls with exists and union all, so I would like you to add the two functions below to fix them, in Firebird2Grammar.php file:

```
public function compileExists(Builder $query)
{
    $select = $this->compileSelect($query);

    return "select 1 \"exists\" from ($select)";
}

protected function wrapUnion($sql)
{
    return $sql;
}
```
*Sorry for my english.

**Comment by harrygulliford** [comment]
This has been fixed in v3 of the package. It is currently in a beta release and should be made generally available soon. https://github.com/harrygulliford/laravel-firebird/tree/next
