### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by qwasyx0** [harrygulliford/laravel-firebird#29]
I upgraded to Laravel 9 in one of my projects and am getting **Undefined property: stdClass::$aggregate** when applying pagination:

row 2660 in vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php 
```
public function getCountForPagination($columns = ['*'])
    {
        $results = $this->runPaginationCountQuery($columns);

        // Once we have run the pagination count query, we will get the resulting count and
        // take into account what type of query it was. When there is a group by we will
        // just return the count of the entire results set since that will be correct.

        if (! isset($results[0])) {
            return 0;
        } elseif (is_object($results[0])) {
            return (int) $results[0]->aggregate;     <-------- Here is exception Undefined property: stdClass::$aggregate
        }

        return (int) array_change_key_case((array) $results[0])['aggregate'];
    }
```

$results[0] in version ^2.3 is:
```
{ 
   aggregate => 0
}
```
But for some reason, in version ^3.0 is:
```
{ 
   AGGREGATE => 0
}
```

This fixes the issue:
```
return isset($results[0]->AGGREGATE) ? (int) $results[0]->AGGREGATE : (int) $results[0]->aggregate;
```

But I'm literally changing core laravel...

Could anything be done about this?

**Comment by qwasyx0** [comment]
Related issue in laravel/framework:

https://github.com/laravel/framework/issues/18460

Suggested is adding this to config/database.php
```
'options'   => array(
  PDO::ATTR_CASE => PDO::CASE_LOWER,
),
```
which solves the issue but I would have to literally rewrite hundreds of Eloquent and QB queries.

Do you @harrygulliford personally use lowercase or uppercase in laravel?

**Comment by harrygulliford** [comment]
Just tagged v3.1.0 to fix the pagination issue. Update your composer dependencies and it should resolve the case issue.

**Comment by qwasyx0** [comment]
That was fast. Thanks! Works like a charm.

**Comment by qwasyx0** [comment]
Looks like it also fixed another issue of mine in laravel livewire https://github.com/rappasoft/laravel-livewire-tables/issues/546#event-5819975482 so double thanks!
