### ISSUE TITLE
Char Vs Varchar - a strange "b" character 

### ISSUE THREAD

**Issue by kobaiashi** [harrygulliford/laravel-firebird#31]
![Schermata del 2022-07-08 14-45-17](https://user-images.githubusercontent.com/58151255/177995450-f58eb5aa-2d97-494e-ad7d-8ae8008c43c4.png)
"harrygulliford/laravel-firebird": "^3.1"
Laravel v9.16.0 (PHP v8.1.2)
Firebird 2.5.4 charset ISO8859_1

if I read a field (CPDES in screenshot) of type Char(50) (ISO8859_1) containing an accented character -> I find a "b" character antecedent to the string 
if the field is a Varchar(200) (LECOM in screenshot) -> no problem

maybe missing a utf8_encode ?

**Comment by harrygulliford** [comment]
See here: https://stackoverflow.com/a/42224939

The `b` prefix on a string in Symfony VarDumper means that it is not valid UTF-8. You could either try a different charset on the driver or use something like https://github.com/neitanod/forceutf8
