### ISSUE TITLE
Why DB::raw() will add a whitespace behind the value? 

### ISSUE THREAD

**Issue by ghost** [harrygulliford/laravel-firebird#33]
As title.
I found out that have extra whitespace added behind the value as the picture below
![image](https://user-images.githubusercontent.com/37526525/189825331-5495e52d-2a42-4b85-b214-7375d7855fdc.png)
![image](https://user-images.githubusercontent.com/37526525/189825495-009f64b2-5e0e-4001-b5be-aa807540b109.png)

Mai I know is this DB::raw issues? or how can I remove that white space in the query?
Thank you. @harrygulliford

**Comment by JustonJ99** [comment]
In addition, the db::raw i write as 'customerType' but why it will auto cast to upper case?
