### ISSUE TITLE
Use for Interbase database connection

### ISSUE THREAD

**Issue by rtfmfm** [harrygulliford/laravel-firebird#34]
Hello,
I'm using Laravel 9 and trying to connect to the Interbase database. It seems that this package is not able to do this. I'm getting `connection rejected by remote interface` I have no problems connecting to a  Firebird database with the same setup.

Please, tell me if I can use this package to connect to Interbase database. Maybe I have a mistake somewhere. Or I should use another package/approach? 

Thank you in advance!

**Comment by harrygulliford** [comment]
The package is not intended to be used with Interbase. It only supports Firebird v2.5, v3, and v4.
