### ISSUE TITLE
could not find driver 

### ISSUE THREAD

**Issue by mbolukbasi** [harrygulliford/laravel-firebird#4]
Hi,
i installed this package and set the database conf. 
add the firebird driver in the database.php and change .env file.

database.php:
    'connections' => [

        'firebird' => [
            'driver'   => 'firebird',
            'host'     => env('DB_HOST', 'localhost'),
            'database' => env('DB_DATABASE', '/path_to/database.fdb'),
            'username' => env('DB_USERNAME', 'sysdba'),
            'password' => env('DB_PASSWORD', 'masterkey'),
            'charset'  => env('DB_CHARSET', 'UTF8'),
        ],

.env:
DB_CONNECTION=firebird
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=C:\Users\Tirad1\Desktop\DATABASE.FDB
DB_USERNAME=SYSDBA
DB_PASSWORD=masterkey
DB_CHARSET=UTF8

but when i want connect the db i got the 'could not find driver' issue? 
firebird 2.5, laravel 5.7, php 7.1 and php extension php_pdo_firebase is active.

Is there any setting other than these?

**Comment by yakupguvenc** [comment]
is problem solved ?
