### ISSUE TITLE
Laravel 11 Support

### ISSUE THREAD

**Issue by tds-dearls** [harrygulliford/laravel-firebird#41]
Is there plans to upgrade this package to support Laravel 11?

**Comment by WalliceCariasPerussio** [comment]
Previsão para correção do erro:
HarryGulliford\Firebird\Schema\Grammars\FirebirdGrammar::compileColumns does not exist.

**Comment by renansteles** [comment]
Is it possible to install this package in Laravel 11?

**Comment by WalliceCariasPerussio** [comment]
Estou usando no laravel 11 existem recursos que não estão funcionando porém não está me atrapalhando o uso consegui resolver de outras formas

**Comment by harrygulliford** [comment]
[v3.3.0](https://github.com/harrygulliford/laravel-firebird/releases/tag/v3.3.0) is now available with added support for Laravel 11 🚀
