### ISSUE TITLE
Method HarryGulliford\Firebird\Schema\Grammars\FirebirdGrammar::compileTables does not exist.

### ISSUE THREAD

**Issue by joaopedrobarbosa** [harrygulliford/laravel-firebird#43]
I'm having this problem when i try to execute a migration.

compilTtables function does not exit at firebirdgrammar file
How to implement that ?

PHP 8.1 and Laravel 10

**Comment by harrygulliford** [comment]
Fixed in [v3.3.0](https://github.com/harrygulliford/laravel-firebird/releases/tag/v3.3.0)
