### ISSUE TITLE
Problem with date

### ISSUE THREAD

**Issue by last1971** [harrygulliford/laravel-firebird#8]
DB::connection('firebird')->select("SELECT * from \"S\" where \"DATA\" > '01.01.2020'");

work correctly

DB::connection('firebird')->table('S')->where('DATA', '>', '\'01.01.2020\'')->get();

not work

I have tried 01.01.2020 and "01.01.2020" but got the same error

  SQLSTATE[HY000]: General error: -303 Dynamic SQL Error SQL error code = -303 arithmetic exception, numeric overflow, or string truncation  (SQL: select * from "S" where "DATA" > '01.01.2020')
or 01.01.2020 or "01.01.2020"

**Comment by rafaels86** [comment]
Have you tried with "2020-01-01"?

**Comment by last1971** [comment]
The Same problem, but I think that problem in driver because in previous driver for PHP7.2 I had similar problem with float
And In not work only with firebird2.0
With 2.5 all right, but base very old and I'm afraid to cross 2.5

**Comment by harrygulliford** [comment]
Sorry, this driver currently only supports the Firebird 2.5 major release. If you're willing to add support for 2.0, feel free to make a PR.

**Comment by last1971** [comment]
Tell me, where is the best way to do this?

**Comment by harrygulliford** [comment]
Here's some links you may find useful for getting started:
- https://laravel-news.com/setup-your-local-environment-for-open-source-package-contributions
- https://opensource.guide/how-to-contribute/
